spring:
  application:
    name: project
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/MIS_D
    username: "root"
    password: 
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
server:
  port: 8081
#  servlet:
#    context-path: /test
